main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.tambah, name='tambah'),
    path('jadwal/', views.jadwal, name='jadwal'),
    path('jadwal/<int:id>/', views.description, name='deskripsi'),
    path('jadwal/<int:id>/delete/', views.delete, name='delete'),
    path('tambah/', views.form, name='form'),

]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

class Matkul(models.Model):
    matkul_name = models.CharField(max_length = 200)
    dosen_name = models.CharField(max_length = 200)
    jumlah_sks = models.IntegerField()
    deskripsi = models.TextField()
    tahun_semester = models.CharField(max_length = 200)
    ruang_kelas = models.CharField(max_length = 200)
# Create your models here.

main/forms.py
from django import forms
from  .models import Matkul

class inputform(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = "__all__"

main/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from .models import Matkul
from .forms import inputform


def tambah(request):
    form = inputform()
    return render(request, 'add.html', {'form' : form})

def jadwal(request):
    matkuls = Matkul.objects.all()
    context = {
        'matkul' : matkuls
    }
    return render(request, 'result.html', context)

def form(request):
    form = inputform(request.POST or None)
    if(form.is_valid() and request.method == "POST"):
        form.save()
        return  HttpResponseRedirect('/jadwal')
    else:
        return HttpResponseRedirect('/')

def description(request, id):
    try:
        matkuls = Matkul.objects.get(id=id)
        context = {
            'matkul' : matkuls
            }
        return render(request,'detail.html', context)
    except Exception:
        return HttpResponseRedirect('/jadwal')

def delete(request, id):
    try:
        Matkul.objects.get(id=id).delete()
        return HttpResponseRedirect('/jadwal')
    except Exception:
        return HttpResponseRedirect('/jadwal')

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <p><img src="{% static 'img/django-logo-negative.svg' %}"></p>
{% endblock content %}

templates/add.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FORM Mata Kuliah</title>
</head>
<body>
{% include "navbar.html" %}
<div class="container-utama">
    <div class="isi2">
        <div>
            <h2>Form Mata Kuliah</h2>
            <form action="/tambah/" method="POST">
                {% csrf_token %}
                <table>
                    {{form.as_table}}
                </table>
                <input type="submit" value="submit">
            </form>
        </div>
    </div>
</div>
{% include "footer.html" %}
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

templates/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Jadwal Mata Kuliah</title>
    <style>
        th{
            text-align: left;
            padding: 20px;
        }
        td {
            padding: 20px;
        }
    </style>
</head>
<body>
{% include "navbar.html" %}
<div class="container-utama">
    <div class="isi2">
        <div>
            <h2 style="margin-left: 8%">Detail</h2>
            <table>
                <tr>
                    <th>Mata Kuliah</th>
                    <td>{{matkul.matkul_name}}</td>
                </tr>
                <tr>
                    <th>Dosen Pengajar</th>
                    <td>{{matkul.dosen_name}}</td>
                </tr>
                <tr>
                    <th>Jumlah SKS</th>
                    <td>{{matkul.jumlah_sks}}</td>
                </tr>
                <tr>
                    <th>Deskripsi</th>
                    <td>{{matkul.deskripsi}}</td>
                </tr>
                <tr>
                    <th>Semester</th>
                    <td>{{matkul.tahun_semester}}</td>
                </tr>
                <tr>
                    <th>Ruang Kelas</th>
                    <td>{{matkul.ruang_kelas}}</td>
                </tr>
                <tr>
                    <td><a href="delete">Delete</a></td>
                </tr>
            </table>
        </div>
    </div>
</div>
{% include "footer.html" %}
</body>
</html>

templates/footer.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
<div class="container-tiga">
    <div class="twitter">
        <table>
            <tr>
                <td><img src="{% static 'pngegg.png' %}" width="30px" height="30px"></td>
                <td>jafar</td>
            </tr>
        </table>
    </div>
    <div class="instagram">
        <table>
            <tr>
                <td><img src="{% static 'instagram.png' %}" width="30px" height="30px"></td>
                <td>jafar</td>
            </tr>
        </table>
    </div>
    <div class="email">
        <table>
            <tr>
                <td><img src="{% static 'email.png' %}" width="30px" height="30px"></td>
                <td>jafar@gmail.com</td>
            </tr>
        </table>
    </div>
</div>
</body>
</html>

templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
<nav>
    <div class="logo">
        <h3>Jafar Abdurrohman</h3>
    </div>
    <ul>
        <li><a href="{% url 'main:tambah' %}">FORM</a></li>
        <li><a href="{% url 'main:jadwal' %}">JADWAL</a></li>
    </ul>
</nav>
</body>
</html>

templates/result.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Jadwal Mata Kuliah</title>
    <style>
        th {
            padding: 20px;
        }

        td {
            padding: 20px;
        }
        .kotak {
            width: 100%;
            display: flex;
            justify-content: center;
        }
    </style>
</head>
<body>
{% include "navbar.html" %}
<div class="container-utama">
    <div class="isi2">
        <div class="kotak">
            {% if matkul %}
            <div>
                <div class="matkul" style="margin-left: 20% ">
                    <h2>Daftar Mata Kuliah</h2>
                </div>
                <table>
                    <tr>
                        <th>Mata Kuliah</th>
                        <th>Dosen Pengajar</th>
                    </tr>
                    {% for form in matkul %}
                    <tr>
                        <td>{{form.matkul_name}}</td>
                        <td>{{form.dosen_name}}</td>
                        <td><a href="{{form.id}}">detail</a></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
            {% else %}
            <h2 style="margin-top: 200px"> Tidak ada matkul yang terdaftar </h2>
            {% endif %}
        </div>
    </div>
</div>
{% include "footer.html" %}
</body>
</html>